kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gateway-service-canary
spec:
  replicas: 1
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway-service
        env: canary
    spec:
      containers:
      - name: gateway-service
        image: cabbottbridge2/gateway-service:1.1.0
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        ports:
        - name: gateway-service
          containerPort: 8080
