kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gateway-service-production
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway-service
        env: production
    spec:
      containers:
      - name: gateway-service
        image: cabbottbridge2/gateway-service:1.1.2
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: 'http://config-service-lb/config'
        ports:
        - name: gateway-service
          containerPort: 8080
