kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: config-service-canary
spec:
  replicas: 1
  template:
    metadata:
      name: config-service
      labels:
        app: config-service
        env: canary
    spec:
      containers:
      - name: config-service
        image: cabbottbridge2/config-service:1.1.0
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        #command: ["/app"]
        ports:
        - name: config-service
          containerPort: 8080
