kind: Service
apiVersion: v1
metadata:
  name: config-service-lb
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: config-service
