server.port: 8080

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    env.enabled: true
    metrics.enabled: true
    prometheus.enabled: true
  metrics.export.prometheus.enabled: true
