server:
  port: 8080

spring.cloud.config.server:
  prefix: /config

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  metrics.export.prometheus.enabled: true
