kind: Service
apiVersion: v1
metadata:
  name: session-service-lb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: session-service
---
kind: Service
apiVersion: v1
metadata:
  name: session-service-hazelcast
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 5701
    targetPort: 5701
    protocol: TCP
  selector:
    app: session-service
